---
author: Christopher Yee
date: 2010-11-24 16:43:48+00:00
layout: post
slug: tsa-a-lesson-in-social-media
title: TSA - A Lesson in Social Media
categories:
- Social Media
---

I gotta give props to them.  The folks over at the Transportation Security Administration probably have one of the toughest social media jobs right now in light of the recent public backlash over enhanced security measures.  Not only do they have to deal with the endless stream of "comments" being posted on the [TSA blog](http://blog.tsa.gov/) but the official TSA twitter account, [TSABlogTeam](http://www.twitter.com/tsablogteam), needs to fend off an attack from all sides via parody accounts.

The most notable ones are [TSAgov](http://www.twitter.com/tsagov), [TSAagent](http://www.twitter.com/tsaagent) and [TSAsupervisor](http://www.twitter.com/tsasupervisor).  It is unclear whether or not they work together but it's interesting (and hilarious) to see how quickly they've garnered a reputation for themselves in the Twitterverse - they even landed on the front page of [TechCrunch](http://techcrunch.com/2010/11/19/rapiscan-yes-really/) over the weekend.

TSAgov acts as the "official" voice of the administration and tweets very clever one liners.  My favorite one is: Tonight we put a few backscatter scanners together and formed a Stargate.  On the other hand, TSAagent and TSAsupervisor act as the foot soldiers.  They "work" together in addressing public concerns with a hint of sarcasm.



In any case, the TSA definitely needs a lesson in [social media](http://www.christopheryee.org/category/social-media/).  The #1 rule, only rule and golden rule of social media is to **never go on the defensive**.  Once you do that - abandon all hope because then it'll be an uphill battle.  The internet is filled with people who will be more than happy to start a flame war if you shrug off their concerns.

For instance, there was a radio interview not too long ago where a lady claims she was [handcuffed to a chair by TSA officials](http://blog.tsa.gov/2010/11/response-to-female-radio-host-cuffed-to.html).  The TSA blogger (aka Blogger Bob) was already on the defensive when he wrote the passenger's account was "inaccurate."  To make matters worse his last couple sentences: You can listen to her radio interview, and then you can view our airport CCTV footage.  We'll let you decide what really happened.

I literally LOL'd.  If they linked the radio interview and the CCTV footage or created their own video to argue against the accusations, readers would fact check on their own.  But by including that defensive comment it exacerbated the already sensitive subject.  What's that common saying?  Out of the frying pan and into the San Francisco conflagration of 1906!

I hope the TSA cleans up their act soon or else they'll be despised more than the IRS - quite a statement!  What are your thoughts?  What could TSA learn from this?  How could they improve before Christmas when it'll be super packed?  Let me know in your comments below and have a happy Thanksgiving!
