---
author: Christopher Yee
date: 2010-09-23 03:45:52+00:00
layout: post
slug: one-month-anniversary-as-an-seo-analyst
title: One Month Anniversary As An SEO Analyst
categories:
- Search Engine Optimization
---

Tomorrow marks my one month anniversary as an [SEO Analyst Intern](http://www.christopheryee.org/job-obtained-seo-analyst-intern/) with [CafePress](http://www.cafepress.com)!  Although it has only been a month, I have learned more in 30 days about [search engine optimization](https://www.christopheryee.org/categories/search-engine-optimization/) than reading 5 books cover to cover relating to the search industry.  Why?  Because of **practical hands on experience**.  I can not stress this enough and believe this is _the_best way to go for search industry newcomers.

By no means am I claiming the books weren't helpful at all and that hands on experience trumps everything else.  Instead, I think of the books as a wire frame that prepared my mind to think like an SEO professional and the actual SEO work as the stuffing that goes into it.  What you have in the end is a master piece!

So what are my thoughts thus far?  It's everything I expected and I'm LOVING it even though there is still a lot for me to learn.  I'm having a lot of fun learning how to analyze search demand for target keywords and performing proper 301 redirects.



In a nut shell, search demand analysis help the decision makers determine whether or not the business should roll out a new product and if so when.  301 redirect is essentially moving (permanently) one website to another website so that you aren't penalized for [duplicate content](http://www.christopheryee.org/domain-change-and-duplicate-content/) by Google.  Both of these can be tedious at times but they are extremely important in the grand scheme of SEO.

Exciting news!  A few days ago, our SEO team had a meeting with the Corporate Partnerships department.  It was in that meeting I learned CafePress has partnerships with hundreds of big name brands, companies and networks!  I was nervous excited when they asked me how social media could be leveraged to boost web traffic and of course I gave them my two pence...and I say that because currently the [pence is worth more than the penny](http://uk.finance.yahoo.com/currencies/converter/#from=GBP;to=USD;amt=.01).

That's not the best part though!  They actually want me to backlink for specific high-end companies.  Woot!  Kind of like an agency....but not!  Score one for me...haha.

Anyways, enough talk.  Check out [The SEO's Handbook - 53 Resources For First Time SEOs](http://www.quicksprout.com/2010/09/21/the-seos-handbook-53-resources-for-first-time-seos/) which is an amazing compilation of must read websites, blogs and guides to the world of search.  I'm out for now!

[Christopher Yee](http://www.christopheryee.org)
