---
author: Christopher Yee
date: 2010-08-24 01:46:50+00:00
layout: post
slug: job-obtained-link-builder-intern
title: 'Job Obtained: Link Builder Intern'
categories:
- Link Acquisition
---

I've done it!  After a couple of months of phone and on-site interviews, I've finally obtained a job in the field of [search engine optimization](http://www.christopheryee.org/category/search-engine-optimization/)!

Last month I completed my first [SEM/PPC job interview](http://www.christopheryee.org/semppc-job-interview-part-1/) with a web marketing company down in Southern California.  Unfortunately, that fell through because I assume relocation was their biggest issue.  I had another phone/on-site interview with a PPC company in Emeryville but I didn't get THAT position because I bombed the interview.....and by bombed I mean I was paralyzed when the interviewer asked me questions I never even expected.  The only thing going through my mind at that time was, "I thought this was an entry level position?!"

In spite of this, I am a firm believer of the phrase, "third time's a charm."  And INDEED it was!  After a series of phone interviews and a two hour long on-site interview, I was offered a position with [CafePress](http://www.cafepress.com/) as a Link Builder Intern.  I will go into the details about my new position in a later post but right now I just want to bask in my glory!

I start tomorrow first thing in the morning.  Wish me luck!
