---
author: Christopher Yee
date: 2010-09-04 02:10:45+00:00
layout: post
slug: job-obtained-seo-analyst-intern
title: 'Job Obtained: SEO Analyst Intern'
categories:
- Search Engine Optimization
---

Today marks the completion of my second week on the job!  And by job I mean as an SEO Analyst Intern at [CafePress](http://www.cafepress.com/).  My previous post, [Job Obtained: Link Builder Intern](http://www.christopheryee.org/job-obtained-link-builder-intern/), stated that I'm a Link Builder.  However, that's incorrect because link building is actually INCLUDED in my duties as an SEO Analyst.  But to tell you the truth, I do WAYYY more than that (I'm not complainin' of course!) and you'll find a short list below.



	
  * In-depth analysis of competitor websites

	
  * Generate, compile and analyze both weekly and monthly web traffic data

	
  * Manage numerous social media accounts (# of accounts classified) across various platforms

	
  * Active link building while keeping keyword anchor texts in mind

	
  * Community outreach

	
  * And more to come as the months progress!


I'll keep you all posted.  Enjoy your Labor Day Weekend because I know I will.   :-]

[Christopher Yee](http://www.christopheryee.org), signing out!
