---
author: Christopher Yee
date: 2010-12-31 22:29:40+00:00
layout: post
slug: funny-interesting-search-phrases-2010
title: Funny and Interesting Search Phrases of 2010
categories:
- Miscellaneous
---

Happy new years eve!!!  Just a few more hours before the start of 2011 and I thought it'd be a great idea to showcase some of the top funny and interesting search phrases of 2010 for [CafePress](http://www.cafepress.com).

I had to sift through copious amounts of data to find them and even then I had a difficult time narrowing them down.  I love looking for these weird tidbits because they are always a nugget for a good laugh.  Moreover, it still boggles my mind on how people are able to find CafePress using search phrases that are totally unrelated to the business.

Without further delay - enjoy!

**Funniest**



	
  * i don't get drunk i get awesome

	
  * vietnam we were winning when i left

	
  * stop me before i volunteer again

	
  * get out of my way i'm fabulous coaster

	
  * ask me about my explosive diarrhea

	
  * zombie hunting permit

	
  * wine em dine em sixty nine em

	
  * i found jesus he was behind the couch

	
  * software is like sex, it's better when it's free

	
  * guns dont kill people dads with pretty daughters do





**Most Interesting**



	
  * cocaine is vitamins for hotel soap

	
  * it's turtles all the way down

	
  * enslave tibet

	
  * jesus hates the cowboys

	
  * virtus junxit mors non separabit

	
  * girls dont poop

	
  * belgium doesn't exist

	
  * coffee you can sleep when you're dead

	
  * denver dumb friends league

	
  * what if the hokey pokey is what it's all about


**Unrelated to CafePress**



	
  * book printing service

	
  * snakes common to virginia

	
  * free sex

	
  * owl porn

	
  * my grass is blue

	
  * i have to return some videotapes

	
  * stephenking.com

	
  * obama's last day in office

	
  * do not stare into laser with remaining good eye

	
  * medical disovories made by accident


Happy new years and good luck to all your endeavors of 2011!
