---
author: Christopher Yee
date: 2010-07-01 09:03:14+00:00
layout: post
slug: let-my-seo-journey-begin
title: Let My SEO Journey Begin
categories:
- Search Engine Optimization
---

Hey there!

Since this is my first blog post for **SEO Christopher Yee**, I find it only appropriate to detail a little bit about myself and what I'll be blogging about.

For starters, my name is [Christopher Yee](http://www.christopheryee.org/) and I was born and raised in good ol' San Francisco, CA. I graduated from the University of the Pacific in Stockton, CA with a double major in International Relations and Asian Language Studies - Mandarin Chinese. Just like all other college graduates out there, I am currently working in an industry wholly unrelated to my major.

There are two main reasons why I started this blog. The first one is my new found interest in [Search Engine Optimization](http://www.christopheryee.org/category/search-engine-optimization/) (SEO) which started about a month ago. I was hooked to the industry when I discovered that one could tweak their websites to make them search engine friendly. To me, this was like playing a video game where I was required to rank up and get to the top of the Search Engine Results Pages (SERPs).



The second reason is my passion to pursue a career in SEO. Initially, I e-mailed a TON of websites looking for work but all of them were unresponsive. I can't blame them for ignoring me either because I'll be the first to admit, the tone of the e-mails sounded a lot like, "Buy 5 Boxes of Viagra and Receive the 6th one FREE!" As a result, I created this blog to establish an online presence for myself so I will have some sort of authority in the world of SEO - not some random nobody sending out e-mails looking for a job.

Whatever the case though, I will be blogging about my learning process as I begin to enter this ever changing field. So sit back, relax, grab a nice cold beer (or tea if you're a member of AA) and join me as I pursue a career in Search Engine Optimization! All I ask from you, the reader, is to correct me of any mistakes I may make because rest assured, there will be plenty of them to go around. LOL.
