---
author: Christopher Yee
date: 2010-09-12 04:14:12+00:00
layout: post
slug: advent-of-google-instant
title: Advent of Google Instant
categories:
- Search Engine Optimization
---

A few days ago, Google introduced [Google Instant](http://www.google.com/instant/) to the search world.  In essence, Google Instant's purpose is to decrease search time for searchers, make accurate predictions and and procure results instantly.  For example, when I type the letter "T" in my search bar, search results show up instantly for "Target."  When I add the letter "I" to the "T," results come up for "Time."  Google Instant is also localized - meaning if you hit "W," the SERP would have weather reports for your city.  Pretty cool stuff if you ask me.

What came after the Google press conference was a flurry of SEO/SEM professionals claiming (or blogging rather) the death of [search engine optimization](http://www.christopheryee.org/category/search-engine-optimization/) and long-tailed keywords.  They make some valid points in their argument but ultimately, it's too early to tell.  In my opinion, we won't know the affect of Google Instant for probably another six months.  Even with Google Instant activated, I have not grown accustomed to typing in one or two letters yet.  I'm still freaked out about how fast the results are showing up haha.



So what does this mean for SEO/SEM folks?  We need to pay attention to what Google Instant is suggesting and implement it into keyword research and analysis.  You may rank #1 for the singular form of a keyword but Google Instant might provide searchers with the plural form of your keyword and thus drawing users away from your website.

Although I'm fairly new to the search industry, I don't think that it will be the death of SEO.  What I love most about this field is how the most successful professionals continue to adapt to the ever changing landscape.  It's true that it can be quite meddlesome but that's what makes it fun.  And guess what?  I love fun!  :)
