---
author: Christopher Yee
date: 2011-12-31 19:54:46+00:00
layout: post
slug: funny-interesting-search-phrases-2011
title: Funny and Interesting Search Phrases of 2011
categories:
- Miscellaneous
---

Happy new years eve, everyone!  To continue my tradition from [last year](http://www.christopheryee.org/funny-interesting-search-phrases-2010/), below are the top funny and interesting search phrases for CafePress in 2011.  Enjoy!

**Funniest**



	
  * Don't ask me, ask google

	
  * The sun is trying to kill me

	
  * Pow! I just shit my pants

	
  * I eat my road kill

	
  * Dick cheney eats kittens

	
  * Barack you like a hurricane

	
  * I'm sick of hearing what rich people think

	
  * Page me like it's 1997

	
  * A little whiskey makes me frisky

	
  * Dinosaurs are jesus ponies





**Most Interesting**



	
  * In beer there is strength, in wine there is wisdom, in water there is bacteria

	
  * Does beer kill dogs?

	
  * Cow tipping in missouri

	
  * Curse you and your inevitable betrayal!

	
  * A is for frog

	
  * Happy mutants for nuclear power

	
  * Brown chicken brown cow

	
  * Very funny scotty now beam down my clothes

	
  * Nuke the south

	
  * 1 by 1 the penguins are stealing my sanity


**Unrelated to CafePress**






	
  * Buy a hyaena

	
  * Vegas pro 10 user manual

	
  * $60 tattoo gun

	
  * San Diego marine boot camp

	
  * Address of the 505th parachute infantry regiment

	
  * Black java chicken

	
  * Pension investment manager

	
  * 1955 seeburg for sale

	
  * Ancient hebrew lexicon of the bible

	
  * Make your own 3D babies


Have fun tonight and may 2012 be better than the last!


