---
author: Christopher Yee
date: 2011-08-27 07:40:08+00:00
layout: post
slug: finally-switching-over-to-wordpress-org
title: Switching Over to WordPress.org
categories:
- Miscellaneous
---

When I first started this blog a little over a year ago, its main purpose was to act as my resume. It was to show potential employers that even though I had no knowledge about the SEO industry, I was very passionate about it. I made it my goal to write at least one blog post per month even though there wasn't any real value to it. But that will all be changing soon as I have finally decided to migrate over to the paid version of WordPress - with new goals in mind.



**Branding and Reputation**
To be successful in the fledgling world of SEO, I have noticed you need to have a strong personal brand and reputation. You need to represent something and fight for what you believe in. For instance, the CEO of SEOmoz, [Rand Fishkin](http://randfishkin.com/blog/) is recognized as an industry leader who is more than willing to share his knowledge with others. [Ross Hudgens](http://www.rosshudgens.com/) is one savvy link builder who advocates for getting $#!t done. And although his posts may be long-winded, [Michael Martinez](http://www.seo-theory.com/) is best known for questioning some of the "best practices" in the industry.

**Helps with Ranking....perhaps?**
With the above goal in mind, removing the wordpress.com extension will not only be pleasing to the eye but I suspect it might even help me rank better. For the past year I pretty much stayed steadily at #23 in Google for "[Christopher Yee](http://www.christopheryee.org)." Although I never did any "real" link building, I have a feeling using free version of wordpress may not help much if you are trying to rank for a competitive keyword such as my name. Maybe because it's a gateway drug for spam bots? Or maybe because it's not a unique domain? Maybe both? Or neither? I don't know but I'll definitely test it out by not link building for another year - LOL.

**Highly Customizable**
I've used the paid version of Wordpress before and I think it's absolutely amazing. The paid version is highly customizable and you can pretty much do anything you want with it - add new widgets, change the CSS, change the layout, implement advertisements, etc. The possibilities are endless! The free version is great and all but as you may have noticed, I am tied down to one single blog theme and no customization is allowed.

That being said, stay tuned as you should see a new domain name very soon. Oh, and I probably won't redirect my old link juice because let's be honest - I never really had any.
