---
author: Christopher Yee
date: 2011-01-28 06:34:13+00:00
layout: post
slug: freelance-seo-important-for-beginners
title: Freelance SEO - Important for Beginners
categories:
- Search Engine Optimization
---

I had a conversation with a friend the other day regarding my freelance [SEO work](http://www.christopheryee.org/example-successful-seo-campaign/).  What he doesn't understand is why I'm doing everything on a volunteer basis and not charging these business owners market rate for my consulting work - or at least at a discounted rate.  I guess he doesn't want to see me do all that work and get nothing in return.

Truth of the matter is I AM getting something in return - experience, testimonials and referrals.  My hands on experience puts SEO theory to practice; written testimonials instill a sense of trust in prospective clients; and referrals show other business owners that I know what I'm doing.

This is why I'm a firm believer that any beginning [SEO analyst](http://www.christopheryee.org/one-month-anniversary-as-an-seo-analyst/) should first go freelance before setting up a price plan. SEO's already have a bad rap sheet in the public's eye and it won't do the industry any good if you charge $2,000 for a website audit which only consists of meta tag changes for all their pages.  Moreover, that's just poor morals as a person in general.



So how does one find freelance work?  Easy - just ask!  Let your family, friends and relatives know what you are doing and how you can help them.  Then take it a bit further by politely asking them to spread the word to their family, friends and relatives.  Word of mouth is the oldest form of marketing so don't underestimate it.

Another great way is to ask the owners of establishments that you frequent.  For example, your local grocery store, drug store, your dog walker or even your dental office.  That's how I received my first gig after all and even though  I didn't receive any form of payment,  I got a lot of free electronic dental equipment! =]

Or, you can just do what I did and provide [free SEO website analysis](http://www.christopheryee.org/free-seo-website-analysis-wayfare-tavern/) (site note: bringing it back soon).

In closing, freelance SEO is a great way for beginning SEOs to get their foot in the door.  You won't be making money right off the bat but it solidifies your reputation and knowledge in the long run.

[Christopher Yee](http://www.christopheryee.org), out!
