---
author: Christopher Yee
date: 2012-05-01 06:19:49+00:00
layout: post
slug: attending-searchlove-sf-conference-distilled
title: Attending SearchLove SF Conference with Distilled
categories:
- Miscellaneous
---

**Update: **Conference has unfortunately been [cancelled](http://www.distilled.net/blog/distilled/searchlove-san-francisco-we-are-sorry-but-we-have-failed/).

<del>I don't have anything major to share this month besides the fact that I will be attending Distilled's [SearchLove conference in San Francisco](http://www.distilled.net/events/searchlove-san-francisco/) (not an affiliate link).  I am super excited about it and can't believe it's less than 1.5 months away!  If you plan to attend please [let me know](http://www.christopheryee.org/contact/) and we'll meet up.</del>

<del>**Date:** June 18th-19th, 2012
**Location:** David Brower Center, Berkeley, CA
**Price:** $849
**Speakers (I look forward to):** Tom Critchlow, Rand Fishkin, Wil Reynolds, Annie Cushing, Justin Briggs, Kate Morris
**Sessions (I look forward to):** Advanced link building strategies, latest ways to measure and action your metrics, link building in the age of social media, integrating social media into your SEO activities</del>



<del>The only gripe I have with their marketing scheme is the fact that** BERKELEY IS NOT SAN FRANCISCO**.  It is a 30-45 minute drive away from The City....what an insult to us San Franciscans so get it right ya bloody blokes!</del>


