---
author: Christopher Yee
date: 2013-03-01 07:01:18+00:00
layout: post
slug: joining-seogadget-family
title: Joining the SEOgadget Family
categories:
- Miscellaneous
---

This post is super late but if you didn't know already I left my short tenure with Macy's earlier this month and joined the SEOgadget family!


<blockquote>You can read my first SEOgadget blog post [here](http://seogadget.com/using-webkit2png-audits-stalking-more/).</blockquote>


I'm helping out [Laura Lippay](https://twitter.com/lauralippay) expand the US office so I'll be getting a taste of both agency and startup life.  Business is already booming and I've got so much work ahead we are looking to hire another Organic Search Strategist.  Yes, that's right - I need a partner in crime!



These are not the official minimum requirements but what I think are the bare essentials.  Need to have a solid understanding of SEO and possess the three traits of success: hardworking, smart and passionate.  Everything else can be taught.

What do you get?  Super supportive management and colleagues (including the UK), weapons-grade computer, [cool office space](http://www.hatcherysf.com/), get to [attend Mozcon 2013](http://seogadget.com/sending-two-of-our-team-to-mozcon/) and a whole lot more.


<blockquote>Everyone on the team has, or had at one point, a cat - you decide what to do with that information.</blockquote>


We're pretty much offering services no other company is doing, innovating SEO techniques you don't read in blogs and building out products vendors don't even have.  It's great stuff so [come join me](http://seogadget.com/seo-jobs/)!!!

Oh, and you have to be based in San Francisco...for now.
