---
author: Christopher Yee
date: 2018-02-20 02:32:29+00:00
layout: post
slug: on-innovation-mini-rant
title: On Innovation (Mini-Rant)
categories:
- Philosophy
---

**TL;DR implementing a system to "drive" (e.g. creating a team or process) and "celebrate" (e.g. recognition awards because let's be real those are just popularity contests) innovation is counter-productive to progress and I firmly believe this can only be fostered via company culture, environment, public forum, mind share, etc.**

What is innovation?  I define it as the application of an idea in a useful and novel way to ensure an entity remains relevant while fundamentally changing the way it is perceived.

I'd go so far as to claim these processes are proposed by innovation/management consultants to attract clientele....completely flies in the face of the spirit of innovation.  What it does instead is it creates a workforce addicted to the dopamine rush of putting a shiny award on their desk.  This ultimately means we only look at what we're not currently doing, what others are doing and then copying them.  That is not innovation - that is incrementality (which is still important for the business).

Based on purely anecdotal evidence, I believe innovation is born from five factors:





 	
  1. An existing problem to solve

 	
  2. Domain expertise

 	
  3. Understanding of market trends

 	
  4. Intellectual curiosity

 	
  5. Obsessive need to prove to nobody but yourself


You can easily hire for #1-#3 on LinkedIn, SimplyHired, Indeed et al., but it's the remaining two that is difficult to replicate because you can't outsource giving a damn.  Individuals who are "innovative" (quotations because they don't self-identify) have a burning desire to seek the truth and will stop at nothing to turn their vision into a reality - it goes beyond personal ambition.  It's about changing the world for the better.

This is why I'm adamantly opposed to an innovation lab/team/process/gang.  Innovation comes from the daily grind of hardworking individuals doing their job, staying late, obsessing over the problem during non-work hours and trying things without permission.  They don't come from companies who "drive" or "celebrate" innovation.  Employees don't need extra time to "innovate."  It doesn't matter if leadership wants to drive innovation or employees claim "we need to be more innovative."  The only thing that matters is a business culture that allows individuals to try new things which haven't been authorized and allowed fail without any consequences.

We don't need a process.  We don't need to measure it.  We don't need a committee so we can pitch our idea and get approved for funding and investment (great first step though).  Good and bad ideas alike will get resolved at the ground level through experimentation, asking questions, feedback loops, making sure it has legs to stand the test of time, etc.  If ideas don't get approved by a committee, the truly innovative one's will work their way around the system anyway - it's in their nature!

Everyone talks about server logs nowadays and although that strategy dates back to 2010, it can be fairly innovative to those green behind the ears.  How does it stack up against our innovation checklist?  Is it useful?  Check.  It is novel?  Check.  Does it ensure the entity remains relevant?  Check.  Does it fundamentally change the way SEO is perceived?  Check - not just about keywords or links!

It derived from ground zero where certain individuals wanted to learn and quantify how search engine crawlers interacted with their website - that is innovation.


