---
title: Code Answers to SQL Murder Mystery
author: Christopher Yee
date: '2019-12-21'
slug: code-answers-to-sql-murder-mystery
categories:
  - Miscellaneous
---

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Pretty fun murder mystery from <a href="https://twitter.com/knightlab?ref_src=twsrc%5Etfw">@knightlab</a> - can you find the killer using <a href="https://twitter.com/hashtag/SQL?src=hash&amp;ref_src=twsrc%5Etfw">#SQL</a>?<a href="https://t.co/vXcMtY2b1c">https://t.co/vXcMtY2b1c</a></p>&mdash; Christopher Yee (@Eeysirhc) <a href="https://twitter.com/Eeysirhc/status/1208109443159691264?ref_src=twsrc%5Etfw">December 20, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


### CLUE #1
There is a **murder** in **SQL City** on **2018-01-15**.

```{sql eval=FALSE}
select *
from crime_scene_report
where type = 'murder'
and city = 'SQL City' 
and date = '20180115'
```


### CLUE #2

Witness 1 lives in the last house on **Northwestern Dr**. Witness 2 is named **Annabel** and lives somehwere on **Franklin Ave**.

```{sql eval=FALSE}
select p.id, 
       p.name, 
       p.address_number, 
       p.address_street_name, 
       i.transcript
from person p

inner join (select person_id, transcript 
            from interview) i on p.id = i.person_id

where p.address_street_name = 'Northwestern Dr'
or (p.address_street_name = 'Franklin Ave' and name like 'Annabel%')
order by address_number desc
```

### CLUE #3
We now know the killer is a **man**, spotted at the local gym on **2018-01-09** with membership ID number starting **48Z** and car license plate includes **H42W**.

```{sql eval=FALSE}

select gfm.id, 
       gfm.person_id, 
       gfm.name, 
       gfm.membership_status, 
       p.license_id, 
       dl.plate_number
from get_fit_now_member gfm

inner join (select membership_id, check_in_date
            from get_fit_now_check_in
            where check_in_date = '20180109'
            and membership_id like '48Z%') gfc on gfm.id = gfc.membership_id

inner join (select id, name, license_id
            from person) p on gfm.person_id = p.id
            and gfm.name = p.name

inner join (select id, plate_number
            from drivers_license
            where gender = 'male'
            and plate_number like '%H42W%') dl on p.license_id = dl.id

where gfm.membership_status = 'gold'
```


<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Apparently there is more to this than meets the eye.... <a href="https://t.co/bfAfmF1oLK">pic.twitter.com/bfAfmF1oLK</a></p>&mdash; Christopher Yee (@Eeysirhc) <a href="https://twitter.com/Eeysirhc/status/1208111156772003840?ref_src=twsrc%5Etfw">December 20, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### CLUE #4

Lets find our next clue to see what Jeremy Bowers had to say:

```{sql eval=FALSE}
select * from interview where person_id = '67318'
```

### CLUE #5
So the mastermind behind this murder is a **woman**, height of **65 to 67** inches, has **red hair**, drives a **Tesla Model S** and attended the **SQL Symphony Concert** at least **3x in December 2017**.
  
```{sql eval=FALSE}
select dl.id, 
       p.name
from drivers_license dl

inner join (select id, name, license_id 
         from person) p on dl.id = p.license_id

inner join (select person_id, count(*) as total
          from facebook_event_checkin
          where event_name = 'SQL Symphony Concert'
          and date between '20171201' and '20171231'
          group by 1
          having count(*) >= 3) fb on p.id = fb.person_id

where dl.height in (65, 66, 67) 
and dl.gender = 'female' 
and dl.car_make = 'Tesla'
```


<blockquote class="twitter-tweet"><p lang="en" dir="ltr">*slowly sips his whiskey in a dark, cigar smoke filled office with the blinds closed* <a href="https://t.co/SyjkcPbOvp">pic.twitter.com/SyjkcPbOvp</a></p>&mdash; Christopher Yee (@Eeysirhc) <a href="https://twitter.com/Eeysirhc/status/1208132543909748736?ref_src=twsrc%5Etfw">December 20, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

