---
title: '10x SEM performance: unlock the power of your own data'
author: Christopher Yee
date: '2020-06-25'
slug: 10x-sem-performance-unlock-the-power-of-your-own-data
categories:
  - Pay Per Click
editor_options: 
  chunk_output_type: console
---



Excerpt from [my original article about using first-party data for custom SEM bidding](https://www.ftoptimize.com/articles/2020/6/25/10x-sem-performance-unlock-the-power-of-your-own-data):

> With each passing year the utility of third-party cookies continues to decline as it faces barriers from web browsers and government regulation. The current system still works and there will be alternatives but it is always best to start preparing for the new status quo.
> 
> FT Optimize believes that the best way to maximize SEM ad revenue is to use first-party data.
> 
> This is because companies gain a competitive advantage when (a) they leverage their own data (b) have tight control over data quality and (c) focus marketing channels to solve their unique business challenges.
> 
> We are not the only ones who believe first-party data is essential. The 2018 survey by [eMarketer](https://www.emarketer.com/content/what-is-the-future-of-third-party-data) highlighted that 85% of US respondents selected the option: “increasing our use of first-party data is a high or critical priority.”

<br> 

## Related

* [Google Ads: digging deeper into target ROAS bidding](https://www.christopheryee.org/blog/google-ads-digging-deeper-into-target-roas-bidding/)

